package routes

import (
	"github.com/M4yankkkk/findash/internal/config"
	"github.com/M4yankkkk/findash/internal/database"
	"github.com/M4yankkkk/findash/internal/handlers"
	"github.com/M4yankkkk/findash/internal/middleware"
	"github.com/M4yankkkk/findash/internal/models"
	"github.com/M4yankkkk/findash/internal/repository"
	"github.com/M4yankkkk/findash/internal/services"
	"github.com/gin-gonic/gin"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// Setup wires all dependencies and registers all routes on the given Gin engine.
func Setup(r *gin.Engine, db *database.DB, cfg *config.Config) {
	// ── Repositories ──────────────────────────────────────────────────────────
	userRepo := repository.NewUserRepository(db)
	auditRepo := repository.NewAuditRepository(db)
	entryRepo := repository.NewEntryRepository(db)
	analyticsRepo := repository.NewAnalyticsRepository(db)

	visibilityRepo := repository.NewVisibilityRepository(db)
	// ── Services ──────────────────────────────────────────────────────────────
	authService := services.NewAuthService(userRepo, auditRepo, cfg.JWTSecret, cfg.JWTExpiryHours)
	userService := services.NewUserService(userRepo, auditRepo, entryRepo, visibilityRepo)
	entryService := services.NewEntryService(entryRepo, auditRepo, visibilityRepo)
	analyticsService := services.NewAnalyticsService(analyticsRepo)

	// ── Handlers ──────────────────────────────────────────────────────────────
	authHandler := handlers.NewAuthHandler(authService)
	userHandler := handlers.NewUserHandler(userService)
	entryHandler := handlers.NewEntryHandler(entryService)
	analyticsHandler := handlers.NewAnalyticsHandler(analyticsService)

	// ── Swagger UI ────────────────────────────────────────────────────────────
	// Available at: GET /swagger/index.html
	// Generated by: swag init -g cmd/main.go
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// ── Health check ──────────────────────────────────────────────────────────
	r.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "ok", "service": "finance-dashboard"})
	})

	api := r.Group("/api/v1")

	// ── Public routes ─────────────────────────────────────────────────────────
	api.POST("/auth/register", authHandler.Register)
	api.POST("/auth/login", authHandler.Login)

	// ── Protected routes (JWT required) ───────────────────────────────────────
	auth := api.Group("")
	auth.Use(middleware.Authenticate(cfg.JWTSecret))
	{
		// Users — admin only
		users := auth.Group("/users")
		users.Use(middleware.RequireAdmin())
		{
			users.GET("", userHandler.ListUsers)
			users.GET("/:id", userHandler.GetUser)
			users.PATCH("/:id/role", userHandler.UpdateRole)
		}

		visibility := auth.Group("/viewer-visibility")
		visibility.Use(middleware.RequireManagerOrAdmin())
		{
			visibility.GET("/viewers", userHandler.ListViewers)
			visibility.GET("/:id/entries", userHandler.GetViewerVisibility)
			visibility.PUT("/:id/entries", userHandler.UpdateViewerVisibility)
		}

		// Entries — all authenticated users, scoping handled in service layer
		entries := auth.Group("/entries")
		{
			entries.POST("", middleware.RequireManagerOrAdmin(), entryHandler.CreateEntry)
			entries.GET("", entryHandler.ListEntries)
			entries.GET("/:id", entryHandler.GetEntry)
			entries.PUT("/:id", middleware.RequireManagerOrAdmin(), entryHandler.UpdateEntry)
			entries.DELETE("/:id", middleware.RequireRole(models.RoleAdmin, models.RoleManager), entryHandler.DeleteEntry)
		}

		// Analytics — manager and admin only
		analytics := auth.Group("/analytics")
		analytics.Use(middleware.RequireManagerOrAdmin())
		{
			analytics.GET("/summary", analyticsHandler.GetSummary)
			analytics.GET("/by-category", analyticsHandler.GetByCategory)
			analytics.GET("/trend", analyticsHandler.GetTrend)
		}
	}
}
